### ISSUE TITLE
咋看不到书页面滚动呢，如何下载？看不到进度

### ISSUE THREAD

**Issue by sdieedu** [liang2kl/wqxuetang-downloader#2]

**Comment by liang2kl** [comment]
正常情况：

![屏幕录制2022-02-19 下午7 31 04](https://user-images.githubusercontent.com/50020539/154799063-369dd826-ef63-4844-92d7-bd22ae8e60a3.gif)

尝试一下刷新页面或者重新启动 Chrome？
